#!/bin/bash
# Determines the users differing between two groups

#####################################################################################
#
# The MIT License (MIT)
#
# Copyright (c) 2015-2017 Jules Kerssemakers / Deutsches Krebsforschungszentrum Heidelberg (DKFZ)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
# OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#####################################################################################


# This script compares the members of two groups side-by-side


if [ "$#" -ne "2" ]; then
  echo "usage: "
  echo "   groupdiff GROUP_LEFT GROUP_RIGHT"
  exit -1;
fi;

# Load the secrets such as password and hostname from somewhere not-in-git
source "${XDG_CONFIG_HOME:-"$HOME"/.config}/ldap-summary.conf"

ldapmembers() {
  GROUP=$1;
  ldapsearch -u -LLL \
    -h $JK_LDAPHOST -w $JK_LDAPPASSWORD \
    -D $JK_BINDDN -b $JK_SEARCHBASE \
    -x \
    cn="$GROUP" member  \
  | sed -r -e 's/\r?\n //g' -e 's/^member: CN=(\w+?),.+$/MEMBER:\1/' \
  | grep '^MEMBER:' \
  | sed 's/^MEMBER://' \
  | sort
}

(
  # Headers
  echo "$1|$2";
  echo "=============|=============";
  # actual queries:
  # joins two post-processed ldapsearch command outputs
  join -a1 -a2 -o 1.1,2.1 -t'|' -e'---' \
    <( ldapmembers $1 ) \
    <( ldapmembers $2 ) \
# pretty-print column widths
) | column -t -s'|'
