#!/bin/bash
# Determines the users differing between two groups

if [ "$#" -ne "2" ]; then
  echo "usage: "
  echo "   groupdiff GROUP_LEFT GROUP_RIGHT"
  exit -1;
fi;

# Load the secrets such as password and hostname from somewhere not-in-git
source "${XDG_CONFIG_HOME:-"$HOME"/.config}/ldap-summary.conf"

ldapmembers() {
  GROUP=$1;
  ldapsearch -u -LLL \
    -h $JK_LDAPHOST -w $JK_LDAPPASSWORD \
    -D $JK_BINDDN -b $JK_SEARCHBASE \
    -x \
    cn="$GROUP" member  \
  | sed -r -e 's/\r?\n //g' -e 's/^member: CN=(\w+?),.+$/MEMBER:\1/' \
  | grep '^MEMBER:' \
  | sed 's/^MEMBER://' \
  | sort
}

(
  # Headers
  echo "$1|$2";
  echo "=============|=============";
  # actual queries:
  # joins two post-processed ldapsearch command outputs
  join -a1 -a2 -o 1.1,2.1 -t'|' -e'---' \
    <( ldapmembers $1 ) \
    <( ldapmembers $2 ) \
# pretty-print column widths
) | column -t -s'|'
