#!/bin/bash

#####################################################################################
#
# The MIT License (MIT)
#
# Copyright (c) 2015-2017 Jules Kerssemakers / Deutsches Krebsforschungszentrum Heidelberg (DKFZ)
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
# of the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF
# OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#####################################################################################


# This script provides a simple wrapper around `ldapsearch`
# You can just enter your filter query (e.g. 'cn=drwho'), and the script
# will handle all the extra bind parameters that LDAP requires
# (loaded from a config file)


# Load the secrets such as password and hostname from somewhere not-in-git
source "${XDG_CONFIG_HOME:-"$HOME"/.config}/ldap-summary.conf"

# actual search
# followed by sed one-liner that rejoins lines broken by the ldap 80-char line limit
# followed by awk to do some layout and base64 decoding
ldapsearch -u -LLL \
  -h $JK_LDAPHOST -w $JK_LDAPPASSWORD \
  -D $JK_BINDDN -b $JK_SEARCHBASE \
  -x \
  "($1)" cn displayName memberOf member description mail uidNumber gidNumber \
  | sed -zr -e "s/\r?\n //g"  -e "s/\r?\n# refldap:.+\r?\n//g" \
  | awk -F'( {2,}|,|:)' \
    'function base_64_decode(encoded) {
       "echo "encoded" | base64 -d" | getline decoded
       return decoded
    }
    function print_formatted_membership(membership_type, cn, ou, whole_line) {
        printf("%-8s:%-28s %-18s full DN: %s\n",
              membership_type, cn, ou,
              gensub("^member(Of)?: ", "", "g", whole_line));
    }
    /^member(Of)?:/                { print_formatted_membership($1, $2, $3, $0); next };
    /^(displayName|description)::/ { print $1 ": " base_64_decode($3);           next };
                                   { print };'
