#!/bin/bash

# Load the secrets such as password and hostname from somewhere not-in-git
source "${XDG_CONFIG_HOME:-"$HOME"/.config}/ldap-summary.conf"

# actual search
# followed by sed one-liner that rejoins lines broken by the ldap 80-char line limit
# followed by awk to do some layout and base64 decoding
ldapsearch -u -LLL \
  -h $JK_LDAPHOST -w $JK_LDAPPASSWORD \
  -D $JK_BINDDN -b $JK_SEARCHBASE \
  -x \
  "($1)" cn displayName memberOf member description mail uidNumber gidNumber \
  | sed -zr -e "s/\r?\n //g"  -e "s/\r?\n# refldap:.+\r?\n//g" \
  | awk -F'( {2,}|,|:)' \
         '/^member(Of)?:/                { printf("%s:%-28s %-18s full DN: %s\n", $1, $2, $3, gensub("^member(Of)?: ", "", "g", $0)); next };
          /^(displayName|description)::/ { "echo "$3" | base64 -d" | getline decoded; print $1 ": " decoded;                     next };
                                         { print };'
