#!/bin/bash

ldapsearch -uLLLh ad.dkfz-heidelberg.de -w logalvsa -x \
  -D CN=ldap,CN=Users,DC=ad,DC=dkfz-heidelberg,DC=de \
  -b 'DC=ad,DC=dkfz-heidelberg,DC=de' \
  "($1)" \
  | sed -zr -e "s/\r?\n //g"  -e "s/\r?\n# refldap:.+\r?\n//g" \
  | awk -F'( {2,}|,|:)' \
         '/^member(Of)?:/                { printf("%s:%-28s %-18s full DN: %s\n", $1, $2, $3, gensub("^member(Of)?: ", "", "g", $0)); next };
          /^(displayName|description)::/ { "echo "$3" | base64 -d" | getline decoded; print $1 ": " decoded;                     next };
                                         { print };' 
